### ISSUE TITLE
Regelung für Rückstufung von Ehrenmitgliedern

### ISSUE THREAD

**Issue by murmurik** [NonsenseInc/satzung#3]
Artikel 3.1.
Satz (7) hinzufügen:
Eine Ehrenmitgliedschaft kann im Einverständnis zwischen dem Mitglied  und dem Vortstand in eine ordentliche Mitgliedschaft umgewandelt werden.

**Comment by NonsenseInc** [comment]
Fix: 11ceaf17d5a31d103f4cb8079e30755f8e4eaf8a
