### ISSUE TITLE
Änderung Artikel 3.2 Satz (3)

### ISSUE THREAD

**Issue by murmurik** [NonsenseInc/satzung#4]
Zum Erwerb der ordentlichen Mitgliedschaft oder Umwandlung der Ehrenmitgliedschaft in eine ordentliche Mitgliedschaft bedarf es bei Minderjährigen der Zustimmung des gesetzlichen Vertreters.

**Comment by NonsenseInc** [comment]
Fix: 11ceaf17d5a31d103f4cb8079e30755f8e4eaf8a
