### ISSUE TITLE
Ergänzungsvorschläge Koxi: Annahme Beitritte, Auflösung juristischer Personen und politische Neutralität

### ISSUE THREAD

**Issue by NonsenseInc** [NonsenseInc/satzung#5]
In den Beitritt:

Über die Annahme der Beitrittserklärung entscheidet der Vorstand mit einfacher Mehrheit.

Vielleicht in den Zweck:

Der Verein ist parteipolitisch und weltanschaulich unabhängig.

In die Mittgliedschaft endet mit:

bzw Auflösung und Erlöschung juristischer Personen

Quelle:

https://www.torservers.net/wiki/verein/satzung

**Comment by NonsenseInc** [comment]
>Über die Annahme der Beitrittserklärung entscheidet der Vorstand mit einfacher Mehrheit.

Momentan haben wir `Über die Aufnahme weiterer Mitglieder entscheidet der Vorstand`. Ich denke nicht dass `mit einfacher Mehrheit` explizit gesagt werden muss. Prinzipiell ist ja der Vorstand nicht ein Vorstandsmitglied sondern alle derer in logische Folge dann mehrheitlich. Das gilt ja für alle Stellen, an denen der Vorstand entscheidet.


>Der Verein ist parteipolitisch und weltanschaulich unabhängig.

Warum? Hilft uns die festlegende Aussage, oder reicht es nicht auch dass es ungeschrieben zutrifft?


>bzw Auflösung und Erlöschung juristischer Personen

Schon vorhanden!

**Comment by timokox** [comment]
"Momentan haben wir Über die Aufnahme weiterer Mitglieder entscheidet der Vorstand. Ich denke nicht dass mit einfacher Mehrheit explizit gesagt werden muss. Prinzipiell ist ja der Vorstand nicht ein Vorstandsmitglied sondern alle derer in logische Folge dann mehrheitlich. Das gilt ja für alle Stellen, an denen der Vorstand entscheidet."

Du solltest dber bedenken, dass das nur der Fall ist, wenn der Vorstand aus 3 Mitgliedern bestehen muss, da sonst auch moeglicherweise eine 2/3 Mehrheit moeglich waere.

**Comment by K0XI** [comment]
"Momentan haben wir Über die Aufnahme weiterer Mitglieder entscheidet der Vorstand. Ich denke nicht dass mit einfacher Mehrheit explizit gesagt werden muss. Prinzipiell ist ja der Vorstand nicht ein Vorstandsmitglied sondern alle derer in logische Folge dann mehrheitlich. Das gilt ja für alle Stellen, an denen der Vorstand entscheidet."

Du solltest dber bedenken, dass das nur der Fall ist, wenn der Vorstand aus 3 Mitgliedern bestehen muss, da sonst auch moeglicherweise eine 2/3 Mehrheit moeglich waere.

**Comment by timokox** [comment]
Was man noch zu den arten der moeglichen ordentlichen mitgliedern hinzufuegen koennte:
Handelsgesellschaften, nicht rechtsfähige Vereine sowie Anstalten und Körperschaften des öffentlichen Rechts werden

und den austritt auch etwas umaendern:
 durch Tod von natürlichen Personen oder durch Auflösung und Erlöschung v
on
juristischen Personen, Handelsgesellschaften, nicht rechtsfähigen Vereinen sowie Anstalten und Körperschaften des öffentlichen
Rechts oder durch Ausschluss; die Beitragspflicht für das laufende Geschäftsjahr bleibt hiervon unberührt. 

Quelle:
https://chaosdorf.de/wp-content/uploads/2012/04/satzung.pdf

**Comment by NonsenseInc** [comment]
>Handelsgesellschaften, [...] sowie Anstalten und Körperschaften des öffentlichen Rechts

...sind juristische Personen.

>nicht rechtsfähigen Vereine

...sind nur wage im BGB definiert und schwer zu berücksichtigen. (siehe https://dejure.org/gesetze/BGB/54.html)

**Comment by NonsenseInc** [comment]
Ich schließe bis neue Einwände kommen.
